Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/12/2022
Var
senha:inteiro


Inicio
escreval("Digite sua senha: ")
leia(senha)
enquanto senha <> 2002 faca
escreval("senha inválida, tente novamente: ", senha)
leia(senha)
fimenquanto
escreval("Acesso permitido")


Fimalgoritmo